# NumPy Arrays

In [41]:
my_list = [1,2,3]

In [42]:
my_list

[1, 2, 3]

In [43]:
import numpy as np

In [44]:
arr = np.array(my_list)

In [45]:
arr

array([1, 2, 3])

In [46]:
my_mat = [[1,2,3], [4,5,6], [7, 8, 9]]

In [47]:
np.array(my_mat)

array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

In [48]:
np.arange(0, 10) # similar to python range function

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.arange(0, 11, 2) 

array([ 0, 2, 4, 6, 8, 10])

In [50]:
np.zeros(3)

array([0., 0., 0.])

In [51]:
np.zeros((2, 3)) # (rows, columns)

array([[0., 0., 0.],
 [0., 0., 0.]])

In [52]:
np.ones(4)

array([1., 1., 1., 1.])

In [53]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
 [1., 1., 1., 1.],
 [1., 1., 1., 1.]])

In [54]:
np.linspace(0, 5, 10) # returns one dimensional vector and ten evenly points from 0 to 5

array([0. , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
 2.77777778, 3.33333333, 3.88888889, 4.44444444, 5. ])

In [55]:
np.linspace(0, 5, 100)

array([0. , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
 0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
 0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
 0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
 1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
 1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
 1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
 1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
 2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
 2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
 2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
 2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
 3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
 3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
 3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737374,
 3.78787879, 3.83838384, 3.88888889, 3.93939394, 3.98989899,
 4.04040404, 4.09090909, 4.14141414, 4.19191919, 4.24242424,
 4.29292929, 4.34343434, 4.39393939, 4.44444444, 4.49494949,
 4.54545455, 4.5959596 , 4.64646465, 4.6969697 , 4.74747475,
 4.7979798 , 4.84848485, 4.8989899 , 4.94949495, 5. ])

In [56]:
# create identity matrix - useful linear algebra problem 
np.eye(4) 

array([[1., 0., 0., 0.],
 [0., 1., 0., 0.],
 [0., 0., 1., 0.],
 [0., 0., 0., 1.]])

In [57]:
np.random.rand(5)

array([0.95851676, 0.32150029, 0.71368466, 0.32893694, 0.6520969 ])

In [58]:
np.random.rand(5,5) # 5v5 matrix

array([[0.03096549, 0.59232787, 0.11691732, 0.84207371, 0.27148218],
 [0.26013153, 0.95240324, 0.79259888, 0.50588033, 0.98127688],
 [0.9943849 , 0.4999976 , 0.08991209, 0.65019886, 0.93092801],
 [0.74891602, 0.89487891, 0.44824743, 0.604662 , 0.19529187],
 [0.83506403, 0.20803755, 0.18988757, 0.61805874, 0.23862785]])

In [59]:
np.random.randn(2) # normal distribution

array([ 0.32238506, -1.7091718 ])

In [60]:
np.random.rand(4, 4)

array([[0.75538328, 0.37789442, 0.87056957, 0.81040865],
 [0.9222525 , 0.28439391, 0.3827665 , 0.88750191],
 [0.27973316, 0.42226162, 0.1093088 , 0.10512155],
 [0.30027613, 0.1347196 , 0.71007699, 0.94175297]])

In [61]:
np.random.randint(1, 100) # generate random from low to high number. incluvise on the lowend but exclusive on the highend

37

In [62]:
np.random.randint(1, 100, 10)

array([97, 92, 32, 51, 83, 35, 89, 94, 24, 14])

In [63]:
arr = np.arange(25)

In [64]:
arr

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,
 17, 18, 19, 20, 21, 22, 23, 24])

In [65]:
ranarr = np.random.randint(0, 50, 10)

In [66]:
ranarr

array([32, 44, 41, 41, 25, 14, 39, 16, 8, 37])

In [67]:
# reshape method = return the same data in a new shape
# number of total rows should be the same as the row x columns
arr.reshape(5,5)

array([[ 0, 1, 2, 3, 4],
 [ 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24]])

In [68]:
ranarr

array([32, 44, 41, 41, 25, 14, 39, 16, 8, 37])

In [69]:
ranarr.max()

44

In [70]:
ranarr.min()

8

In [71]:
ranarr.argmax() # return the index location

1

In [72]:
ranarr.argmin() # return the index location

8

In [73]:
arr.shape

(25,)

In [74]:
arr = arr.reshape(5,5)

In [75]:
arr.shape

(5, 5)

In [76]:
arr.dtype # data type of the array

dtype('int64')

In [77]:
from numpy.random import randint

In [78]:
randint(2, 10)

6