# NumPy Operations

In [4]:
import numpy as np

In [5]:
arr = np.arange(0, 11)

In [6]:
arr

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [7]:
arr + arr # add two arrays together

array([ 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20])

In [8]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
arr * arr

array([ 0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100])

In [10]:
arr + 100 # add 100 to all elements

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [11]:
arr * arr

array([ 0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100])

In [12]:
arr * 100

array([ 0, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000])

In [13]:
1/0

ZeroDivisionError: ZeroDivisionError: division by zero

In [14]:
arr / arr

<ipython-input-14-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan, 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
1 / arr

<ipython-input-15-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([ inf, 1. , 0.5 , 0.33333333, 0.25 ,
 0.2 , 0.16666667, 0.14285714, 0.125 , 0.11111111,
 0.1 ])

In [16]:
arr ** 2

array([ 0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100])

In [17]:
# universal array functions (ufunc)

np.sqrt(arr)

array([0. , 1. , 1.41421356, 1.73205081, 2. ,
 2.23606798, 2.44948974, 2.64575131, 2.82842712, 3. ,
 3.16227766])

In [18]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
 5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
 2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [19]:
np.max(arr)

10

In [20]:
np.sin(arr)

array([ 0. , 0.84147098, 0.90929743, 0.14112001, -0.7568025 ,
 -0.95892427, -0.2794155 , 0.6569866 , 0.98935825, 0.41211849,
 -0.54402111])

In [21]:
np.log(arr)

<ipython-input-21-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([ -inf, 0. , 0.69314718, 1.09861229, 1.38629436,
 1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
 2.30258509])